version: '3'
services:
  db_test:
    container_name: iot_cloud_db_test
    volumes:
      - data_test:/var/lib/postgresql/data_test
    expose:
      - 5432
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TESTING_DB_NAME: "testing"
      ATTR_AUTH_DB_NAME: "attr_auth"
      TEST_DB_ATTR_AUTH_NAME: "attr_auth_testing"
      POSTGRES_DB: postgres
      PGPORT: 5432
    networks:
      - test
  web:
    container_name: iot_cloud_web
    working_dir: /app
    volumes:
      - ./app:/app
    networks:
      - test

    environment:
      - DOCKER_TLS_VERIFY=True
      - COMPOSE_TLS_VERSION=TLSv1_2
      - PYTHONDONTWRITEBYTECODE=False
      - FLASK_ENV=docker
      - FLASK_DEBUG=1
      - FLASK_APP=app.app_setup:create_app('development')
    command: bash -c "while ping -c1 web_test &>/dev/null; do sleep 1; done && flask run --host=0.0.0.0 --port=443 --no-reload"
    depends_on:
      - web_test
  mqtt:
    container_name: iot_cloud_mqtt
    restart: always
    ports:
    - "8883:8883"
    - "9001:9001"
    environment:
    - DOCKER_TLS_VERIFY=True
    - COMPOSE_TLS_VERSION=TLSv1_2
    volumes:
    - ./mosquitto/config:/etc/mosquitto
    - ./mosquitto/data:/mosquitto/data
    - ./mosquitto/log:/mosquitto/log
    - ./mosquitto/certs:/mosquitto/certs
    command: ["mosquitto", "-c", "/etc/mosquitto/mosquitto.conf"]
    networks:
    - test
  nginx:
    container_name: iot_cloud_nginx
    ports:
    - "443:443"
    volumes:
    - ./webserver/conf.d:/etc/nginx/conf.d
    - ./webserver/ssl/:/etc/ssl/
    depends_on:
    - web
    networks:
    - test
  web_test:
    container_name: iot_cloud_web_test
    working_dir: /app
    volumes:
    - ./app:/app
    - ./client:/client
    - './tests:/tests'
    - /tests/test_client/
    user: ${CURRENT_UID}
    environment:
    - DOCKER_TLS_VERIFY=True
    - COMPOSE_TLS_VERSION=TLSv1_2
    - PYTHONDONTWRITEBYTECODE=False
    command: pytest ../tests --color=yes --log-level=ERROR --log-cli-format="%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)" --log-cli-date-format="%Y-%m-%d %H:%M:%S" --junitxml=/tests/reports/test_report.xml --cov=/app --cov-report term --cov-report xml:/tests/reports/cov_report.xml -W ignore::DeprecationWarning -W ignore::passlib.exc.PasslibHashWarning
    depends_on:
      - db_test
    networks:
      - test

volumes:
  data_test: {}

networks:
  test:
    driver: bridge